# Generated by Django 4.0.3 on 2022-04-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_post_likes_user_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created',
        ),
    ]
